env:
  browser: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
rules:
  indent:
    - 0
  quotes:
    - error
    - single
  semi:
    - 0
  no-case-declarations:
    - 0
